import type { Metadata } from "next";
import "~/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="sv" data-scroll-behavior="smooth">
      <body className={`antialiased flex flex-col min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
